image: node:latest

stages:
    - build
    - test
    - deploy

build:
    stage: build
    script:
        - C:\Users\krist\AppData\Roaming\npm\node_modules\yarn\bin\yarn install
        - C:\Users\krist\AppData\Roaming\npm\node_modules\yarn\bin\yarn build
        - echo "Build successful."


test:
    stage: test
    script:
        - C:\Users\krist\AppData\Roaming\npm\node_modules\yarn\bin\yarn test
        - echo "Build successful."

deploy:
    stage: deploy
    script:
        - docker build . -t s3ip-front-end
        - echo "Build successful."